from django.db import models
from ..models import MyUser,Location_info,UnitInfo,Business_Sol_info

class BudgetInfo(models.Model):
    bf_Airport_Handling_Charges = models.FloatField(blank=True, null=True,default=0.0)
    bf_Crane_Handling_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Forklift_Handling_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Handling_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Packing_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Warehouse_Handling_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Warehouse_Loading_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Warehouse_Storage_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_Warehouse_Unloading_Charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_updated_by = models.ForeignKey(MyUser,blank=True, null=True, on_delete=models.CASCADE)
    bf_start_date_year = models.DateField(default='2024-01-01')
    bf_audit_fees = models.FloatField(blank=True, null=True, default=0.0)
    bf_bad_debts = models.FloatField(blank=True, null=True, default=0.0)
    bf_bank_charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_celebration_expenses= models.FloatField(blank=True, null=True, default=0.0)
    bf_consultancy_charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_directors_remuneration = models.FloatField(blank=True, null=True, default=0.0)
    bf_insurance_car = models.FloatField(blank=True, null=True, default=0.0)
    bf_interest_on_statutory_dues = models.FloatField(blank=True, null=True, default=0.0)
    bf_professional_legal_charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_subscription_membership = models.FloatField(blank=True, null=True, default=0.0)
    bf_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_bonus_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_EDLI_contribution_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_employer_contribution_to_ESI_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_employer_contribution_to_PF_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_EPF_admin_charges_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_gratuity_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_salaries_wages_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_dept_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_bonus_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_EDLI_contribution_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_employer_contribution_to_ESI_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_employer_contribution_to_PF_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_EPF_admin_charges_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_gratuity_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_salaries_wages_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_interest_on_borrowings = models.FloatField(blank=True, null=True, default=0.0)
    bf_interest_on_other_loans = models.FloatField(blank=True, null=True, default=0.0)
    bf_fixed = models.FloatField(blank=True, null=True, default=0.0)
    bf_depreciation = models.FloatField(blank=True, null=True, default=0.0)
    bf_software_AMC_charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_insurance_warehouse = models.FloatField(blank=True, null=True, default=0.0)
    bf_rates_taxes = models.FloatField(blank=True, null=True, default=0.0)
    bf_rent_premises = models.FloatField(blank=True, null=True, default=0.0)
    bf_security_service_charges = models.FloatField(blank=True, null=True, default=0.0)
    bf_manpower_supply_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_variable = models.FloatField(blank=True, null=True, default=0.0)
    bf_crane_handling_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_diesel_expenses_forklift = models.FloatField(blank=True, null=True, default=0.0)
    bf_forklift_handling_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_fumigation_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_updated_at = models.DateField(null=True, auto_now=True)
    bf_oe_Fixed = models.FloatField(blank=True, null=True, default=0.0)
    bf_housekeeping_salary = models.FloatField(blank=True, null=True, default=0.0)
    bf_insurance_corp_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_insurance_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_internet_data_card_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_rent_plant_machinery = models.FloatField(blank=True, null=True, default=0.0)
    bf_system_amc = models.FloatField(blank=True, null=True, default=0.0)
    bf_oe_variable = models.FloatField(blank=True, null=True, default=0.0)
    bf_advertisement_business_promotion = models.FloatField(blank=True, null=True, default=0.0)
    bf_conveyance_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_diesel_expenses_gense = models.FloatField(blank=True, null=True, default=0.0)
    bf_handling_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_hotel_boarding_lodging_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_office_repairs_maintenance = models.FloatField(blank=True, null=True, default=0.0)
    bf_office_supplies_general_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_postage_courier = models.FloatField(blank=True, null=True, default=0.0)
    bf_power_fuel = models.FloatField(blank=True, null=True, default=0.0)
    bf_printing_stationery = models.FloatField(blank=True, null=True, default=0.0)
    bf_service_maintenance_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_staff_welfare_staff = models.FloatField(blank=True, null=True, default=0.0)
    bf_telephone_mobile_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_training_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_travelling_expenses = models.FloatField(blank=True, null=True, default=0.0)
    bf_location = models.ForeignKey(Location_info, null=True, on_delete=models.CASCADE, default='')
    bf_unit_reference = models.ForeignKey(UnitInfo, null=True, on_delete=models.CASCADE, default='')
    bf_company = models.ForeignKey(Business_Sol_info, on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return f"budget form at {self.bf_Airport_Handling_Charges}"
