from django.db import models
from ..models import MyUser,StatusList,VehicletypeInfo,CustomerInfo,TrbusinesstypeInfo,CustomerdepartmentInfo,GstexcemptionInfo

class Dispatch_info(models.Model):
    dispatch_job_no = models.CharField(blank=False, null=False, max_length=20)
    dispatch_invoice = models.CharField(blank=False, null=False,max_length=20)
    dispatch_customer = models.ForeignKey(CustomerInfo,on_delete=models.CASCADE, default='')
    dispatch_customer_type = models.ForeignKey(TrbusinesstypeInfo,on_delete=models.CASCADE, default='')
    dispatch_depature_date = models.CharField(blank=True, null=True,max_length=20)
    dispatch_department = models.ForeignKey(CustomerdepartmentInfo,on_delete=models.CASCADE, default='')
    dispatch_shipper = models.CharField(blank=True, null=True, max_length=20)
    dispatch_consignee = models.CharField(blank=True, null=True, max_length=20)
    dispatch_no_of_pkg = models.IntegerField(blank=True, null=True)
    dispatch_weight = models.IntegerField(blank=True, null=True)
    dispatch_driver = models.CharField(blank=True, null=True, max_length=20)
    dispatch_contact_number = models.CharField(blank=True, null=True, max_length=20)
    dispatch_DL_number = models.CharField(blank=True, null=True, max_length=20)
    dispatch_otl = models.CharField(blank=True, null=True, max_length=20)
    dispatch_transporter = models.CharField(blank=True, null=True, max_length=100)
    dispatch_truck_number = models.CharField(blank=True, null=True, max_length=20)
    dispatch_truck_type = models.ForeignKey(VehicletypeInfo, on_delete=models.CASCADE, default='')
    dispatch_status = models.ForeignKey(StatusList, on_delete=models.CASCADE, default=6,null=True)
    dispatch_sticker_pasted_BVM = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE, null=True,related_name='dispatch_sticker_pasted_BVM', db_column='dispatch_sticker_pasted_BVM')
    dispatch_HAWB = models.CharField(blank=True, null=True, max_length=20)
    dispatch_MAWB = models.CharField(blank=True, null=True, max_length=20)
    dispatch_destination = models.CharField(blank=True, null=True, max_length=20)
    dispatch_comments = models.CharField(blank=True, null=True, max_length=20)
    dispatch_GRN = models.CharField(blank=True, null=True, max_length=20)
    dispatch_cargo_picked = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE,null=True,related_name='dispatch_cargo_picked', db_column='dispatch_cargo_picked')
    dispatch_num = models.CharField(blank=True, null=True, max_length=20)
