from django.db import models
from ..models import Location_info, UnitInfo,YesNoInfo,GoodnotgoodInfo

class Gatemeetinginfo(models.Model):
    gm_branch = models.ForeignKey(Location_info, on_delete=models.CASCADE, blank=True, null=True)
    gm_unit = models.ForeignKey(UnitInfo, on_delete=models.CASCADE, blank=True,null=True)
    gm_date = models.DateField(blank=True,null=True)
    gm_Previous_night_security = models.CharField(max_length=100, null=True,default='')
    gm_Previous_night_security_remark = models.TextField(blank=True, null=True)
    gm_Any_incident_of_previous_day = models.CharField(max_length=100, null=True,default='')
    gm_Any_incident_of_previous_day_remark = models.TextField(blank=True, null=True)
    gm_Previous_day_WH_closing_checklist  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Previous_day_WH_closing_checklist',db_column='gm_Previous_day_WH_closing_checklist', default=2)
    gm_Current_day_WH_opening_checklist  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Current_day_WH_opening_checklist',db_column='gm_Current_day_WH_opening_checklist', default=2)
    gm_WMS_updation_till_yesterday = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_WMS_updation_till_yesterday',db_column='gm_WMS_updation_till_yesterday', default=2)
    gm_DSR_sent_to_all_customers_yesterday = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_DSR_sent_to_all_customers_yesterday',db_column='gm_DSR_sent_to_all_customers_yesterday', default=2)
    gm_Stock_informed_to_Customer = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Stock_informed_to_Customer',db_column='gm_Stock_informed_to_Customer', default=2)
    gm_Pre_alerts_customers_inbound_outbound = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Pre_alerts_customers_inbound_outbound',db_column='gm_Pre_alerts_customers_inbound_outbound', default=2)
    gm_Inbound_documents_scanned  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Inbound_documents_scanned',db_column='gm_Inbound_documents_scanned', default=2)
    gm_Outbound_documents_scanned  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Outbound_documents_scanned',db_column='gm_Outbound_documents_scanned', default=2)
    gm_Cleanliness_of_warehouse  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Cleanliness_of_warehouse',db_column='gm_Cleanliness_of_warehouse', default=2)
    gm_Facility_checklist_provided  = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Facility_checklist_provided',db_column='gm_Facility_checklist_provided', default=2)
    gm_Space_issues = models.CharField(max_length=100, null=True,default='')
    gm_Space_issues_remark = models.TextField(blank=True, null=True)
    gm_HPTE_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_HPTE_condition',db_column='gm_HPTE_condition', default=1)
    gm_Fork_Lift_check = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Fork_Lift_check',db_column='gm_Fork_Lift_check', default=1)
    gm_Weight_scale_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Weight_scale_condition',db_column='gm_Weight_scale_condition', default=1)
    gm_Fire_Extinguisher = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Fire_Extinguisher',db_column='gm_Fire_Extinguisher', default=1)
    gm_CCTV_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_CCTV_condition',db_column='gm_CCTV_condition', default=1)
    gm_Lights_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Lights_condition',db_column='gm_Lights_condition', default=1)
    gm_UPS_invertor_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_UPS_invertor_condition',db_column='gm_UPS_invertor_condition', default=1)
    gm_Genset_condition = models.ForeignKey(GoodnotgoodInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Genset_condition',db_column='gm_Genset_condition', default=1)
    gm_Stock_of_Diesel_Genset = models.ForeignKey(YesNoInfo, blank=True, null=True, on_delete=models.CASCADE, related_name='gm_Stock_of_Diesel_Genset',db_column='gm_Stock_of_Diesel_Genset', default=2)
    gm_Security_attendance = models.CharField(max_length=100, null=True,default='')
    gm_Staff_attendance = models.CharField(max_length=100, null=True,default='')
    gm_Labour_attendance = models.CharField(max_length=100, null=True,default='')
    gm_Todays_crucial_shipment_handled = models.CharField(max_length=100, null=True,default='')
    gm_Todays_crucial_shipment_handled_remark = models.TextField(blank=True, null=True)
    gm_Yesterdays_pending = models.CharField(max_length=100, null=True,default='')
    gm_Yesterdays_pending_remark = models.TextField(blank=True, null=True)
    gm_Customer_complaints_received = models.CharField(max_length=100, null=True,default='')
    gm_Customer_complaints_received_remark = models.TextField(blank=True, null=True)
    gm_Audit_score_plan = models.CharField(max_length=100, null=True,default='')
    gm_Audit_score_plan_remark = models.TextField(blank=True, null=True)
    gm_Floor_pallets_Stock = models.IntegerField(null = True,blank=True,default=0)
    gm_Approval_DGM_pending = models.CharField(max_length=100, null=True, default='')
    gm_Approval_DGM_pending_remark = models.TextField(blank=True, null=True)
    gm_Pending_task_today  = models.CharField(max_length=100, null=True, default='')
    gm_Pending_task_today_remark = models.TextField(blank=True, null=True)
    gm_email_count = models.IntegerField(blank=True, null=True, default=0)

