from django.db import models
from ..models import VhmanufacturerInfo,VehiclemodelInfo,OwnershipInfo,BodyInfo,VehicletypeInfo,AxletypeInfo,FueltypeInfo,VehiclecolourInfo,Insurance_Type,PermittypeInfo,StatusList

class VehiclemasterInfo(models.Model):
    vm_vehiclemanufacturer = models.ForeignKey(VhmanufacturerInfo, on_delete=models.CASCADE, default='')
    vm_vehiclemodel = models.ForeignKey(VehiclemodelInfo, on_delete=models.CASCADE, default='')
    vm_ownership = models.ForeignKey(OwnershipInfo, on_delete=models.CASCADE, default='')
    vm_tonnage = models.CharField(max_length=10,default = '')
    vm_containersize = models.CharField(max_length=10,default = '')
    vm_capacity = models.CharField(max_length=30)
    vm_category = models.CharField(max_length=30)
    vm_body = models.ForeignKey(BodyInfo,on_delete=models.CASCADE, default='')
    vm_vehicletype = models.ForeignKey(VehicletypeInfo,on_delete=models.CASCADE, default='')
    vm_axletype = models.ForeignKey(AxletypeInfo,on_delete=models.CASCADE, default='')
    vm_registrationnumber = models.CharField(max_length=30)
    vm_millage = models.CharField(max_length=30)
    vm_cost = models.CharField(max_length=30)
    vm_fueltype = models.ForeignKey(FueltypeInfo, on_delete=models.CASCADE, default='')
    vm_yearofdepreciation = models.CharField(max_length=30)
    vm_ofdepreciation = models.CharField(max_length=30)
    vm_vehiclecolour = models.ForeignKey(VehiclecolourInfo, on_delete=models.CASCADE, default='')
    vm_registrationdate = models.CharField(max_length=30)
    vm_valueofvehicle = models.CharField(max_length=30)
    vm_chassisnumber = models.CharField(max_length=30)
    vm_enginenumber = models.CharField(max_length=30)
    vm_batterynumber = models.CharField(max_length=30)
    vm_batterywarrantydate = models.CharField(max_length=30)
    vm_numberoftyres = models.CharField(max_length=30)
    vm_tyremake = models.CharField(max_length=30)
    vm_stephanietyremake = models.CharField(max_length=30)
    vm_stephanietyre = models.CharField(max_length=30)
    vm_tyre1 = models.CharField(max_length=30)
    vm_tyre2 = models.CharField(max_length=30)
    vm_tyre3 = models.CharField(max_length=30)
    vm_tyre4 = models.CharField(max_length=30)
    vm_fireextinguisher = models.CharField(max_length=30)
    vm_fireextexpirydate = models.CharField(max_length=30)
    vm_firstaidkit = models.CharField(max_length=30)
    vm_fakexpirydate = models.CharField(max_length=30)
    vm_gprstrackingid = models.CharField(max_length=30)
    vm_toolboxcontent1 = models.CharField(max_length=30)
    vm_toolboxcontent2 = models.CharField(max_length=30)
    vm_toolboxcontent3 = models.CharField(max_length=30)
    vm_toolboxcontent4 = models.CharField(max_length=30)
    vm_toolboxcontent5 = models.CharField(max_length=30)
    vm_gprssimid = models.CharField(max_length=30)
    vm_insurancetype = models.ForeignKey(Insurance_Type, on_delete=models.CASCADE, default='')
    vm_company = models.CharField(max_length=30)
    vm_policy = models.CharField(max_length=30)
    vm_policyexpirydate = models.CharField(max_length=30)
    vm_premium = models.CharField(max_length=30)
    vm_icvvalue = models.CharField(max_length=30)
    vm_ncb = models.CharField(max_length=30)
    vm_insurancecopy = models.ForeignKey(StatusList, on_delete=models.CASCADE, default='',related_name='vm_insurancecopy', db_column='vm_insurancecopy')
    vm_rtoname = models.CharField(max_length=30)
    vm_fcdate = models.CharField(max_length=30)
    vm_receipt = models.CharField(max_length=30)
    vm_fcamount = models.CharField(max_length=30)
    vm_fcexpirydate = models.CharField(max_length=30)
    vm_fccopy = models.ForeignKey(StatusList, on_delete=models.CASCADE, default='',related_name='vm_fccopy', db_column='vm_fccopy')
    vm_agencyname = models.CharField(max_length=30)
    vm_agencycharges = models.CharField(max_length=30)
    vm_roadtaxamount = models.CharField(max_length=30)
    vm_roadtaxexpirydate = models.CharField(max_length=30)
    vm_roadtaxreceipt = models.CharField(max_length=30)
    vm_roadtaxreceiptdate = models.CharField(max_length=30)
    vm_roadtaxcopy = models.ForeignKey(StatusList, on_delete=models.CASCADE, default='',related_name='vm_roadtaxcopy', db_column='vm_roadtaxcopy')
    vm_permittype = models.ForeignKey(PermittypeInfo, on_delete=models.CASCADE, default='')
    vm_permitexpirydate = models.CharField(max_length=30)
    vm_permit = models.CharField(max_length=30)
    vm_permitamount = models.CharField(max_length=30)
    vm_permitdate = models.CharField(max_length=30)
    vm_permitcopy = models.ForeignKey(StatusList, on_delete=models.CASCADE, default='',related_name='vm_permitcopy', db_column='vm_permitcopy')
    vm_pollutioncertificate = models.CharField(max_length=30)
    vm_pollutioncertificateamt = models.CharField(max_length=30)
    vm_pollutioncertificatedate = models.CharField(max_length=30)
    vm_pollutioncertificatecopy = models.ForeignKey(StatusList, on_delete=models.CASCADE, default='',related_name='vm_pollutioncertificatecopy', db_column='vm_pollutioncertificatecopy')
    vm_mobileappdeviceid = models.CharField(max_length=30)
    vm_bpclcard = models.CharField(max_length=30)
    vm_fastagid = models.CharField(max_length=30)
    vm_primarydrivername = models.CharField(max_length=30)
    vm_primarydrivermob = models.CharField(max_length=30)
    vm_potenialrevenue = models.CharField(max_length=30)
    vm_secondarydrivername = models.CharField(max_length=30)
    vm_secondarydrivermob = models.CharField(max_length=30)
    vm_budgetexpense = models.CharField(max_length=30)









    def __str__(self):
        return self.en_enquirynumber