from django.db import models
from django.utils.timezone import now
from ..models import Pregateintruckinfo,Gatein_pre_info,YesNoInfo,MyUser,Stock_type,CustomerdepartmentInfo,TrbusinesstypeInfo,CustomerInfo,DamagereportInfo,Loadingbay_Info,Gatein_info,Dispatch_info,VehicletypeInfo,Fumigation_ActionInfo,Packagetype_info,StatusList,DamageInfo,Location_info,UnitInfo,BayInfo,Check_in_out,GstexcemptionInfo,UOM,StackingInfo

class warehouse_goodsnew_info(models.Model):
    whn_job_no = models.CharField(blank=True, null=True, max_length=200)
    whn_gate_injob_no_id = models.ForeignKey(Gatein_info, on_delete=models.CASCADE, related_name='whn_job_no_id',db_column='whn_job_no_id', null=True, blank=True)
    whn_lb_job_no_id = models.ForeignKey(Loadingbay_Info, on_delete=models.CASCADE, related_name='whn_lb_job_no_id',db_column='whn_lb_job_no_id', null=True, blank=True)
    whn_Dam_rep_job_num_id = models.ForeignKey(DamagereportInfo, on_delete=models.CASCADE,related_name='whn_Dam_rep_job_num_id', db_column='whn_Dam_rep_job_num_id',null=True, blank=True)
    whn_goods_invoice = models.CharField(max_length=200)
    whn_goods_package_type = models.ForeignKey(Packagetype_info, on_delete=models.CASCADE, default='',blank=True, null=True,)
    whn_goods_volume_weight = models.FloatField(default=0.0)
    whn_goods_status = models.ForeignKey(StatusList, on_delete=models.CASCADE,default=6,null=True,related_name='whn_goods_status',db_column='whn_goods_status')
    whn_weights_deviation = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE,null=True,related_name='whn_weights_deviation',db_column='whn_weights_deviation',default=2)
    whn_dimension_deviation = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE,null=True,related_name='whn_dimension_deviation',db_column='whn_dimension_deviation',default=2)
    whn_no_of_units_deviation = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE,null=True,related_name='whn_no_of_units_deviation',db_column='whn_no_of_units_deviation',default=2)
    whn_damages= models.ForeignKey(DamageInfo, on_delete=models.CASCADE, null=True,related_name='whn_damages',db_column='whn_damages',default=6)
    whn_mismatches= models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE, null=True,related_name='whn_mismatches',db_column='whn_mismatches',default=2)
    whn_fumigation_process = models.ForeignKey(GstexcemptionInfo, on_delete=models.CASCADE, null=True, blank=True,related_name='whn_fumigation_process',db_column='whn_fumigation_process',default=1)
    whn_fumigation_action = models.ForeignKey(Fumigation_ActionInfo, on_delete=models.CASCADE, null=True)
    whn_fumigation_date=models.DateTimeField(null=True,blank=True)
    whn_uom = models.ForeignKey(UOM, on_delete=models.CASCADE, null=True, related_name='whn_uom',db_column='whn_uom')
    whn_chargeable_weight = models.FloatField(null=True,default=0.0)
    whn_cbm = models.FloatField(null=True,default=0.0)
    whn_branch = models.ForeignKey(Location_info, null=True,on_delete=models.CASCADE, default='')
    whn_unit = models.ForeignKey(UnitInfo,null=True, on_delete=models.CASCADE, default='')
    whn_bay= models.ForeignKey(BayInfo,null=True, on_delete=models.CASCADE, default='')
    whn_available_area = models.FloatField(null=True,default=0.0)
    whn_available_volume = models.FloatField(null=True,default=0.0)
    whn_goods_area = models.FloatField(null=True,default=0.0)
    whn_check_in_out= models.ForeignKey(Check_in_out, on_delete=models.CASCADE, null=True, default=1,related_name='whn_check_in_out',db_column='whn_check_in_out')
    whn_customer_name = models.ForeignKey(CustomerInfo,on_delete=models.CASCADE, blank=False, null=False,default='')
    whn_customer_type = models.ForeignKey(TrbusinesstypeInfo,on_delete=models.CASCADE, blank=False, null=False,default='')
    whn_stack_layer = models.ForeignKey(StackingInfo, null=True, on_delete=models.CASCADE, default='')
    whn_checkin_time = models.DateTimeField(null=True)
    whn_checkout_time = models.DateTimeField(null=True)
    whn_storage_time = models.FloatField(blank=True, null=True,default=0.0)
    whn_qr_rand_num = models.CharField(blank=True, null=True, max_length=200)
    whn_dispatch_num = models.CharField(blank=True, null=True, max_length=200)
    whn_consigner = models.CharField(max_length=200,default='')
    whn_consignee = models.CharField(max_length=200,default='')
    whn_comments = models.TextField(blank=True, null=True)
    whn_invoice_value= models.FloatField(blank=True, null=True,default=0.0)
    whn_invoice_amount_inr = models.FloatField(blank=True, null=True,default=0.0)
    whn_voucher_num = models.CharField(blank=True, null=True, max_length=200)
    whn_po_num = models.CharField(max_length=100,default="NA")
    whn_invoice_weight_unit = models.FloatField(blank=True, null=True,default=0.0)
    whn_invoice_qty = models.IntegerField(blank=True, null=True)
    whn_gross_weight = models.FloatField(default=0.0)
    whn_total_qty = models.IntegerField(blank=True, null=True, default=0)
    whn_loading_charge_unit = models.FloatField(blank=True, null=True, default=0.0)
    whn_total_loading_cost = models.FloatField(blank=True, null=True, default=0.0)
    whn_storage_cost_per_day = models.FloatField(blank=True, null=True, default=0.0)
    whn_storage_cost_total = models.FloatField(blank=True, null=True, default=0.0)
    whn_forklift_cost = models.FloatField(blank=True, null=True, default=0.0)
    whn_forklift_cost_l2hr = models.FloatField(blank=True, null=True, default=0.0)
    whn_forklift_cost_g2hr = models.FloatField(blank=True, null=True, default=0.0)
    whn_crane_cost = models.FloatField(blank=True, null=True, default=0.0)
    whn_crane_cost_l2h = models.FloatField(blank=True, null=True, default=0.0)
    whn_crane_cost_g2h = models.FloatField(blank=True, null=True, default=0.0)
    whn_total_invoice_cost = models.FloatField(blank=True, null=True, default=0.0)
    whn_truck_type = models.ForeignKey(VehicletypeInfo, on_delete=models.CASCADE, null=True,blank=True)
    whn_dispatch_id= models.ForeignKey(Dispatch_info, on_delete=models.CASCADE, null=True,blank=True)
    whn_department = models.ForeignKey(CustomerdepartmentInfo,on_delete=models.CASCADE, blank=False, null=False,default="")
    whn_comodity = models.ForeignKey(Stock_type, on_delete=models.CASCADE,null=True)
    whn_created_at = models.DateTimeField(null=True, auto_now_add=True)
    whn_updated_at = models.DateTimeField(null=True, auto_now=True)
    whn_updated_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=True)
    whn_cargo = models.ForeignKey(YesNoInfo,blank=True, null=True,default='1', on_delete=models.CASCADE)
    whn_dock_in_date_time = models.DateTimeField(default=now)
    whn_destination = models.CharField(blank=True, null=True, max_length=100)
    whn_hawb = models.CharField(max_length=100,default='NA')
    whn_pre_id = models.ForeignKey(Gatein_pre_info, on_delete=models.CASCADE,default='',null=True)
    whn_truck_number_n = models.ForeignKey(Pregateintruckinfo, on_delete=models.CASCADE,default='',null=True)
    whn_gatein_status = models.ForeignKey(StatusList, on_delete=models.CASCADE, default=6,null=True)

    class Meta:
        ordering = ["whn_job_no"]

    def __str__(self):
        return self.whn_job_no

