from django.db import models
from ..models import Stock_movement_type,Stock_type,Currency_type
class Warehouse_stock_info(models.Model):
    wh_stock_movement_type = models.ForeignKey(Stock_movement_type, on_delete=models.CASCADE, blank=True, null=True,max_length=20)
    wh_stock_type = models.ForeignKey(Stock_type, on_delete=models.CASCADE, blank=True, null=True,max_length=20)
    wh_stock_invoice = models.CharField(blank=False, null=False,max_length=20)
    wh_stock_customer_name = models.CharField(blank=False, null=False, max_length=20)
    wh_stock_arrival_date = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_unloading_start_time = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_unloading_end_time = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_FRD_time = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_invoice_value = models.IntegerField(blank=True, null=True)
    wh_stock_amount_in = models.IntegerField(blank=True, null=True)
    wh_stock_invoice_currency = models.ForeignKey(Currency_type, on_delete=models.CASCADE, blank=True, null=True)
    wh_stock_transporters = models.CharField(blank=True, null=True,max_length=100)
    wh_stock_truck_number = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_truck_type = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_consigner_name = models.CharField(blank=True, null=True,max_length=100)
    wh_stock_consignee_name = models.CharField(blank=True, null=True,max_length=100)
    wh_stock_docs_received = models.CharField(blank=True, null=True,max_length=10)
    wh_stock_HAWB = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_MAWB = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_destination = models.CharField(blank=True, null=True,max_length=30)

    wh_stock_case_number = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_invoice_weight = models.IntegerField(blank=True, null=True)
    wh_stock_CBM = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_eway_bill = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_fumigation_status = models.CharField(blank=True, null=True,max_length=20)

    wh_stock_location = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_days_in_wh = models.IntegerField(blank=True, null=True)
    wh_stock_ship_date = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_out_time = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_labels_pasted_by = models.CharField(blank=True, null=True,max_length=20)
    wh_stock_remarks = models.CharField(blank=True, null=True,max_length=250)
    wh_stock_driver_name = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_driver_contact = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_driver_lic = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_driver_name_out = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_driver_contact_out = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_driver_lic_out = models.CharField(blank=True, null=True, max_length=250)
    wh_stock_arrival_date_out = models.CharField(blank=True, null=True, max_length=20)
    wh_stock_unloading_start_time_out = models.CharField(blank=True, null=True, max_length=20)
    wh_stock_unloading_end_time_out = models.CharField(blank=True, null=True, max_length=20)
    wh_stock_FRD_time_out = models.CharField(blank=True, null=True, max_length=20)
    wh_stock_transporters_out = models.CharField(blank=True, null=True, max_length=100)
    wh_stock_truck_number_out = models.CharField(blank=True, null=True, max_length=20)
    wh_stock_truck_type_out = models.CharField(blank=True, null=True, max_length=20)