# Generated by Django 6.0.4 on 2026-07-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(help_text='e.g., TMS, WMS, PMS', max_length=50)),
                ('module_name', models.CharField(help_text='e.g., Enquiry, Vendor', max_length=100)),
                ('record_id', models.CharField(help_text='ID of the modified record', max_length=100)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['system_name', 'module_name', 'record_id'], name='audit_syste_system__0ae116_idx'), models.Index(fields=['timestamp'], name='audit_syste_timesta_857bbd_idx')],
            },
        ),
    ]
