# Generated by Django 6.0.4 on 2026-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='systemauditlog',
            name='audit_syste_system__0ae116_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemauditlog',
            name='audit_syste_timesta_857bbd_idx',
        ),
        migrations.RenameField(
            model_name='systemauditlog',
            old_name='action_type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='systemauditlog',
            old_name='user',
            new_name='changed_by',
        ),
        migrations.RenameField(
            model_name='systemauditlog',
            old_name='new_data',
            new_name='changed_data',
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='model_name',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemauditlog',
            name='module_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemauditlog',
            name='record_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='systemauditlog',
            name='system_name',
        ),
    ]
