from .sub_forms.AssetinfoaddForm_form import AssetinfoaddForm
from .sub_forms.AssignassetaddForm_form import AssignassetaddForm
from .sub_forms.CreateUserForm_form import CreateUserForm,UserextForm
from .sub_forms.DepartmentaddForm_form import DepartmentaddForm
from .sub_forms.EmployeeaddForm_form import EmpeditForm,UserexteditForm,EmployeeaddForm
from .sub_forms.GoodsaddForm_form import GoodsaddForm
from .sub_forms.InsuranceaddForm_form import InsuranceaddForm
from .sub_forms.LocationaddForm_form import LocationaddForm
from .sub_forms.ProductaddForm_form import ProductaddForm
from .sub_forms.ServiceaddForm_form import ServiceaddForm
from .sub_forms.StockaddForm_form import StockaddForm
from .sub_forms.VendoraddForm_form import VendoraddForm
from .sub_forms.ProducttypeaddForm_form import ProducttypeaddForm
from .sub_forms.CountryForm import CountryaddForm
from .sub_forms.StateForm import StateaddForm
from .sub_forms.CityForm import CityaddForm
from .sub_forms.InsurancetypeaddForm_form import InsurancetypeaddForm
from .sub_forms.StudForm_form import StudaddForm
from .sub_forms.peoform_form import PeoaddForm
from .sub_forms.damageaddform_form import DamageaddForm
from .sub_forms.damagereportaddform_form import DamagereportaddForm
from .sub_forms.locationmasteraddform_form import LocationmasteraddForm
from .sub_forms.UnitForm_Form import UnitaddForm
from .sub_forms.BayaddForm_Form import BayaddForm
from .sub_forms.StatusaddForm_Form import StatusaddForm
from .sub_forms.CustomertypeaddForm_Form import CustomertypeaddForm
from .sub_forms.whratemasteraddform_Form import WhratemasteraddForm
from .sub_forms.designationForm import DesignationaddForm
from .sub_forms.whstoragetypeform_Form import WhstoragetypeaddForm
from .sub_forms.roleaddform_Form import RoleaddForm
from .sub_forms.whstoragetypeform_Form import WhstoragetypeaddForm
from .sub_forms.roleaddform_Form import RoleaddForm
from .sub_forms.GateinForm_form import GateinaddForm

