from django.db import models
from django.contrib.auth.models import User
from .sub_models.insurance_type_mod import Insurance_Type
from .sub_models.status_list_mod import StatusList
from .sub_models.country_mod import Country
from .sub_models.state_mod import State
from .sub_models.city_mod import City
from .sub_models.prod_type_mod import Prod_Type
from .sub_models.prod_cat_mod import Prod_Cat
from .sub_models.location_info_mod import Location_info
from .sub_models.vendor_info_mod import Vendor_info
from .sub_models.department_info_mod import Department_info
from .sub_models.product_info_mod import Product_info
from .sub_models.insurance_info_mod import Insurance_Info
from .sub_models.my_user_mod import MyUser
from .sub_models.asset_info_mod import AssetInfo
from .sub_models.service_info_mod import Service_Info
from .sub_models.enquire_info_mod import Enquiry_Info
from .sub_models.stock_movement_type_mod import Stock_movement_type
from .sub_models.stock_type_mod import Stock_type
from .sub_models.currency_type_mod import Currency_type
from .sub_models.package_type_mod import Package_type
from .sub_models.warehouse_goods_info_mod import Warehouse_goods_info
from .sub_models.warehouse_stock_info_mod import Warehouse_stock_info
from .sub_models.assign_asset_info_mod import Assign_asset_info
from .sub_models.employee_mod import Employee
from .sub_models.student_mod import Stud_reg
from .sub_models.peo_mod import Peo_reg
from .sub_models.damage_mod import DamageInfo
from .sub_models.damagereport_mod import DamagereportInfo
from .sub_models.locationmaster_mod import LocationmasterInfo
from .sub_models.user_ext_mod import User_extInfo
from .sub_models.unit_info_mod import UnitInfo
from .sub_models.Bay_info_mod import BayInfo
from .sub_models.Status_info_mod import StatusInfo
from .sub_models.Customertype_info_mod import CustomertypeInfo
from .sub_models.whstoragetype_mod import WhstoragetypeInfo
from .sub_models.Whratemaster_mod import WhratemasterInfo
from .sub_models.designation_mod import DesignationInfo
from .sub_models.role_mod import RoleInfo