from .sub_views.assetinfo_view import assetinfo_add,asset_list,asset_delete
from .sub_views.assign_asset_add_view import assign_asset_add,assign_asset_delete,assign_asset_list_new
from .sub_views.department_add_view import department_add,department_delete,department_list
from .sub_views.goods_add_view import goods_add,goods_list,goods_delete
from .sub_views.goods_check_view import goods_check
from .sub_views.home_page_view import home_page
from .sub_views.insurance_add_view import insurance_add,insurance_delete,insurance_list
from .sub_views.location_add_view import location_add,location_list,location_delete
from .sub_views.login_page_view import login_page
from .sub_views.login_page_view_new import login_page_new,home_page_new
from .sub_views.logout_page_view import logout_page
from .sub_views.print_pdf_view import print_pdf
from .sub_views.product_add_view import product_add,product_list,product_delete
from .sub_views.producttype_add_view import producttype_list,producttype_delete,producttype_add
from .sub_views.qr_code_asset_view import qr_code_asset
from .sub_views.qr_code_goods_view import qr_code_goods
from .sub_views.registration_page_view import registration_page
from .sub_views.reports_view import reports
from .sub_views.service_add_view import service_add,service_list,service_delete
from .sub_views.stock_add_view import stock_add,stock_list,stock_delete
from .sub_views.user_add_view import user_add,user_list,user_delete
from .sub_views.vendor_add_view import vendor_add,vendor_list,vendor_delete
from .sub_views.country_add_view import country_list,country_delete,country_add
from .sub_views.state_add_view import state_list,state_delete,state_add
from .sub_views.city_add_view import city_add,city_list,city_delete
from .sub_views.insurancetype_add_view import insurancetype_add,insurancetype_delete,insurancetype_list
from .sub_views.stud_add_view import stud_add,stud_delete,stud_list
from .sub_views.peo_add_view import peo_add,peo_list,peo_delete
from .sub_views.damage_add_view import damage_add,damage_list,damage_delete
from .sub_views.damagereport_add_view import damagereport_add,damagereport_list,damagereport_delete
from .sub_views.locationmaster_add_view import locationmaster_add,locationmaster_list,locationmaster_delete
from .sub_views.employee_add_view import emp_add,emp_list,emp_delete,emp_registration_page