from .sub_views.send_department_email import send_department_email,send_department_email_html
from .sub_views.warehouse_email_view import warehouse_send_email_view
from .sub_views.assetinfo_view import assetinfo_add,asset_list,asset_delete,asset_search,un_assigned_asset_list
from .sub_views.assign_asset_add_view import assign_asset_add,assign_asset_delete,assign_asset_list_new
from .sub_views.department_add_view import department_add,department_delete,department_list
from .sub_views.goods_check_view import goods_check
from .sub_views.home_page_view import home_page,wh_e_way_bill_list,edit_wh_e_way_bill_list,open_requirements_list,customer_contract_rate_due_days,customer_contract_rate_dues_list
from .sub_views.insurance_add_view import insurance_add,insurance_delete,insurance_list
from .sub_views.location_add_view import location_add,location_list,location_delete
from .sub_views.login_page_view import login_page,get_units_for_user
# from .sub_views.login_page_view_new import login_page_new,home_page_new,get_units
from .sub_views.logout_page_view import logout_page
from .sub_views.driver_login_view import driver_login, driver_logout
from .sub_views.driver_dashboard_view import driver_dashboard
from .sub_views.print_pdf_view import print_pdf
from .sub_views.product_add_view import product_add,product_list,product_delete
from .sub_views.producttype_add_view import producttype_list,producttype_delete,producttype_add
from .sub_views.qr_code_asset_view import qr_code_asset
from .sub_views.qr_code_goods_view import qr_code_goods
from .sub_views.registration_page_view import registration_page
from .sub_views.reports_view import reports,damage_report_pdf,warehouse_reports,space_utilization_reports,space_availability_reports,stock_value_reports,damage_reports_list,deviation_report,export_stockreport_to_csv,revenue_report,expense_report,goods_in_out_reports_list,stock_value_send_email_view,transport_reports
from .sub_views.service_add_view import service_add,service_list,service_delete
from .sub_views.stock_add_view import stock_add,stock_list,stock_delete
from .sub_views.user_add_view import user_add,user_list,user_delete
from .sub_views.vendor_add_view import vendor_add,vendor_list,vendor_delete
from .sub_views.country_add_view import country_list,country_delete,country_add
from .sub_views.state_add_view import state_list,state_delete,state_add
from .sub_views.city_add_view import city_add,city_list,city_delete
from .sub_views.insurancetype_add_view import insurancetype_add,insurancetype_delete,insurancetype_list
from .sub_views.stud_add_view import stud_add,stud_delete,stud_list
from .sub_views.peo_add_view import peo_add,peo_list,peo_delete
from .sub_views.damage_add_view import damage_add,damage_list,damage_delete
from .sub_views.picture_view import picture_add,picture_list,picture_delete
from .sub_views.damagereport_add_view import damagereport_add,damagereport_list
from .sub_views.locationmaster_add_view import locationmaster_add,locationmaster_list,locationmaster_delete,load_customer_model,warehousevolme_area_calc
from .sub_views.goods_add_view import goods_add,goods_list,goods_delete,goods_update,wh_excess_stock_email
from .sub_views.employee_add_view import emp_add,emp_list,emp_delete,emp_registration_page
from .sub_views.unit_add_view import unit_add,unit_list,unit_delete
from .sub_views.Bay_add_view import bay_add,bay_list,bay_delete
from .sub_views.status_add_view import status_add,status_list,status_delete
from .sub_views.Customertype_add_view import customertype_add,customertype_list,customertype_delete
from .sub_views.whratemasteradd_view import whratemaster_add,whratemaster_list,whratemaster_delete
from .sub_views.designation_add_view import designation_add,designation_list,designation_delete
from .sub_views.whstoragetype_add_view import whstoragetype_add,whstoragetype_list,whstoragetype_delete
from .sub_views.role_add_view import role_add,role_list,role_delete
from .sub_views.password_reset_request_view import (
	password_reset_confirm,
	password_reset_otp_verify,
	password_reset_request,
)
from .sub_views.wh_job_add_view import wh_job_add,wh_job_list,wh_job_delete
from .sub_views.gatein_add_view import gatein_add,gatein_list,gatein_delete,load_pre_gate_in,get_queryset,load_pre_gate_in_truck_details,get_shippers,get_consignees,gatein_pdf,gatein_pdf_download,gatein_upload_attachment,gatein_delete_attachment
from .sub_views.loadingbay_add_view import loadingbay_add,load_currency_value
from .sub_views.enquirynote_add_view import enquirynote_add,enquirynote_list,enquirynote_delete,consignment_note_connect,get_customer_details,enquirynote_nav,fetch_enquiry_locations
from .sub_views.consignmentdetail_add_view import consignmentdetail_add,consignmentdetail_list,consignmentdetail_list_ajax,consignmentdetail_delete,consignmentdetail_nav,consignment_note_pdf,vehicle_allotted,consignmentdetail_cancel,get_vehicle_type,consignment_pdf_download,consignmentdetail_enquiry
from .sub_views.customername_add_view import customername_add,customername_list,customername_delete
from .sub_views.vehiclecategory_add_view import vehiclecategory_add,vehiclecategory_list,vehiclecategory_delete
from .sub_views.customerdepartment_add_view import customerdepartment_add,customerdepartment_list,customerdepartment_delete
from .sub_views.vehicletype_add_view import vehicletype_add,vehicletype_list,vehicletype_delete
from .sub_views.tripdetail_add_view import tripdetail_add,tripdetail_list,tripdetail_list_ajax,tripdetail_delete,tripdetail_nav,load_vehicle_details,trip_email,load_truck_details,fleet_management_view,tripdetail_enquiry,get_sim_tracking_data,get_customer_ref,get_last_reported_km,trip_send_loading_report_mail,trip_send_trip_started_mail,trip_send_unloading_report_mail,trip_send_trip_closed_mail,get_trip_email_recipients
from .sub_views.movementtype_add_view import movementtype_add,movementtype_list,movementtype_delete
from .sub_views.trbusinesstype_add_view import trbusinesstype_add,trbusinesstype_list,trbusinesstype_delete
from .sub_views.tripclosure_add_view import tripclosure_add,tripclosure_list,tripclosure_list_ajax,tripclosure_delete,tripclosure_nav,transport_calculate_trip_charges,tripclosure_enquiry,get_fastag_toll_cost_ajax,calculate_toll
from .sub_views.vhmanufacturer_add_view import vhmanufacturer_add,vhmanufacturer_list,vhmanufacturer_delete
from .sub_views.vehiclemodel_add_view import vehiclemodel_add,vehiclemodel_list,vehiclemodel_delete
from .sub_views.ownership_add_view import ownership_add,ownership_list,ownership_delete
from .sub_views.body_add_view import body_add,body_list,body_delete
from .sub_views.axletype_add_view import axletype_add,axletype_list,axletype_delete
from .sub_views.fueltype_add_view import fueltype_add,fueltype_list,fueltype_delete
from .sub_views.vehiclecolour_add_view import vehiclecolour_add,vehiclecolour_list,vehiclecolour_delete
from .sub_views.permittype_add_view import permittype_add,permittype_list,permittype_delete
from .sub_views.vehiclemaster_add_view import vehiclemaster_add,vehiclemaster_list,vehiclemaster_delete
from .sub_views.rtratemaster_add_view import rtratemaster_add,rtratemaster_list,rtratemaster_delete
from .sub_views.gstexcepmtion_add_view import gstexcepmtion_add,gstexcepmtion_list,gstexcepmtion_delete
from .sub_views.gstmodel_add_view import gstmodel_add,gstmodel_list,gstmodel_delete
from .sub_views.paymenttype_add_view import paymenttype_add,paymenttype_list,paymenttype_delete
from .sub_views.crcountfrom_add_view import crcountfrom_add,crcountfrom_list,crcountfrom_delete
from .sub_views.customer_add_view import customer_add,customer_list,customer_delete,customer_attach_add,customer_attach_list,customer_attach_delete,customer_attach_cancel,customer_contract_rate_report,get_customer_pan_gst
from .sub_views.materialhandling_add_view import materialhandling_list,materialhandling_delete,materialhandling_add
from .sub_views.packagetype_add_view import packagetype_list,packagetype_delete,packagetype_add
from .sub_views.currency_type_add_view import currencytype_add,currencytype_list,currencytype_delete
from .sub_views.stock_type_add_view import stocktype_add,stocktype_delete,stocktype_list
from .sub_views.warehouse_add_view import warehousein_add,load_units,load_bays,load_area_volume,load_units_origin,load_bays_origin,warehouseout_add,warehouseout_cancel,warehouse_jobs_add
from .sub_views.storage_add_view import storage_list
from .sub_views.dispatch_add_view import dispatch_list,dispatch_delete,dispatch_add,dispatch_goods_list,dispatch_remove_goods,dispatch_add_goods,qr_dispatch_decoder,dispatch_search,dispatch_invoice_job_update,dispatch_stock_list,dispatch_gatepass_pdf,dispatch_goods_back,dispatch_gatepass_pdf_download,dispatch_partial_goods,dispatch_upload_attachment,dispatch_delete_attachment
from .sub_views.message_test import message_test
from .sub_views.pregateintruck_view import pregateintruck_add,pregateintruck_list,pregateintruck_delete,pregateintruckdetails_list,pregateintruck_cancel,add_transporter,pregatein_gatepass_pdf,pregatein_gatepass_pdf_download,truck_send_email_view
from .sub_views.dsr_add_view import dsr_reports,dsr_send_email_view
from .sub_views.gatein_pre_add_view import gatein_pre_add,gatein_pre_list,gatein_pre_delete,pre_gatein_search,gate_in_email
from .sub_views.invoice_view import invoice_list,invoice_add,invoice_delete,shipper_invoice_list,shipper_invoice_goods_add,shipper_invoice_goods_remove,load_whrate_model,case_to_case_invoice_list_open,dedicated_invoice_list_open,exclusive_invoice_list_open,invoice_report,shipper_invoice_export_excel,invoice_export_excel
from .sub_views.expense_view import expense_add,expense_list,expense_delete,expense_search, expense_ext_add, expense_ext_list, expense_ext_delete, expense_ext_cancel
from .sub_views.salesinfo_view import sales_add,sales_list,sales_delete,sales_comments_list,sales_comments_add,sales_comments_delete,sales_search,sales_comments_search,sales_reports,sales_multiple_item_add,sales_multiple_item_list,sales_multiple_item_delete,sales_multiple_item_cancel
from .sub_views.ininspectionreport_view import ininspectreport_add,ininspectreport_list,ininspectreport_delete
from .sub_views.ouinspectionreport_view import ouinspectreport_add,ouinspectreport_list,ouinspectreport_delete
from .sub_views.materialstock_view import materialstock_add,materialstock_list,materialstock_delete
from .sub_views.packingjobs_view import packingjobs_add,packingjobs_list,packingjobs_delete
from .sub_views.arinfo_view import ar_add,ar_list,ar_delete
from .sub_views.sales_target_add_view import sales_target_add,sales_target_list,sales_target_delete
from .sub_views.arcomments_add_view import arcomments_add,arcomments_list,arcomments_delete
from .sub_views.Requirements_add_view import requirements_add,requirements_list,requirements_delete,requirements_search
from .sub_views.pk_needassessment_view import needassessment_add,needassessment_list,needassessment_delete,na_dimension_add,na_dimension_list,na_dimension_delete,na_dimension_cancel,Pkcosting_delete,Pkcostingsummary_delete,Pkpurchaseorder_delete,Pkpurchaseorder_dim_delete,Pkquotation_delete,Pkquotation_summary_delete,Pkneedassessment_dim_delete,need_assessment_print_pdf,get_tracker_flags
from .sub_views.pk_openingstock_view import openingstock_add,openingstock_list,openingstock_delete
from .sub_views.pk_stockpurchases_view import stockpurchases_add,stockpurchases_list,stockpurchases_delete,stockpurchases_cancel,fetch_part_code_details, stock_usage_breakdown
from .sub_views.pk_purchaseorder_view import purchaseorder_add,purchaseorder_list,purchaseorder_delete,pk_get_customer,po_dimension_add,po_dimension_cancel,po_dimension_list,po_dimension_delete,pk_get_po_requirement_type, pk_create_batch_job, pk_get_po_items_for_job
from .sub_views.pk_quotes_view import quotes_add,quotes_list,quotes_delete
from .sub_views.pk_costing_view import costing_add,costing_list,costing_delete,load_stock_description,load_pk_wood_description,costing_cancel,pk_item_search_page,modify_dimensions_view,pk_item_search_page_costing,pk_get_item_description,pk_get_po_requirement_type,pk_store_po_dimension_id,pk_return_excess_to_stock
from .sub_views.pk_costing_summary_view import costingsummary_add,costingsummary_list,costingsummary_delete,pk_costing_summary_check_unique_field,pk_bvm_invoice_pdf,pk_costing_get_customer,pk_bvm_invoice_excel,export_cost_assessment_to_excel,get_partcode_summary
from .sub_views.vehicle_allotment_view import vehicle_allotment_list,vehicle_allotment_add,vehicle_allotment_delete,vehicle_allotment_nav,load_vehicle_source,load_vehicle_number,load_driver_details,vehicle_requested,vehicle_type_counts,get_remaining_quantity,get_vendor_buy_rate,get_vendor_sale_rate,vehicle_allotment_enquiry,vendor_filter,vehicle_allotment_email,get_vendor_by_vehicle,vehicle_allotment_replace,vehicle_allotment_driver_replace
from .sub_views.fuelfilling_view import fuelfilling_add,fuelfilling_list,fuelfilling_delete,load_location,fetch_bunk_details,fuelfilling_export_excel
from .sub_views.bunkname_view import bunkname_add,bunkname_list,bunkname_delete
from .sub_views.places_view import places_add,places_list,places_delete
from .sub_views.enquirynote_vehicle_view import enquirynotevehicle_add,enquirynotevehicle_list,enquirynotevehicle_delete,enquirynotevehicle_cancel
from .sub_views.consignmentgoods_view import consignmentgoods_add,consignmentgoods_list,consignmentgoods_delete,consignmentgoods_nav,consignmentgoods_cancel,consignmentgoods_back,add_description,add_consigner,add_consignee,consignmentgoods_upload_attachment,consignmentgoods_delete_attachment
from .sub_views.pk_stock_vendor_view import pk_stock_vendor_add,pk_stock_vendor_list,pk_stock_vendor_delete
from .sub_views.pk_quotation_view import pk_quotation_add,pk_quotation_list,pk_quotation_delete,pK_quotation_cancel,pk_get_pk_requirement_type,pk_store_na_dimension_id
from .sub_views.iou_view import iou_add,iou_list,iou_delete,get_full_name_iou
from .sub_views.pk_quotation_summary_view import pk_quotationsummary_add,pk_quotationsummary_list,pk_quotationsummary_delete,pk_quotation_summary_check_unique_field,pk_bvm_quotation_pdf, pk_quotationsummary_clone, pk_quotationsummary_clone_po
from .sub_views.pk_retrival_view import pk_retrival_add,pk_retrival_list,pk_retrival_delete,pK_retrival_cancel
from .sub_views.pk_stock_return_view import  pk_return_list
from .sub_views.pk_stock_acceptance_view import pK_acceptance_cancel,pk_acceptance_add,pk_acceptance_delete,pk_acceptance_list
from .sub_views.comments_add_view import comments_list,comments_delete,comments_add,comments_cancel
from .sub_views.chart_view import bar_chart,bar_chart_data
from .sub_views.task_add_view import task_add,task_list,task_delete,get_requirement_description
from .sub_views.timesheet_add_view import timesheet_add,timesheet_list,timesheet_delete,timesheet_nav,timesheet_report
from .sub_views.ml_category_view import create_product,ml_product_list,ml_product_delete
from .sub_views.businessrevenue_view import business_revenue_add,business_revenue_list,business_revenue_delete
from .sub_views.pk_gate_pass_returnable_view import gate_return_add,gate_return_list,gate_return_delete,gate_return_pdf,gate_return_employee_id,gate_pass_get_jobs_by_customer,gate_pass_get_job_details,update_dc_item_financials
from .sub_views.pk_deliverychallan_add_view import delivery_challan_add,delivery_challan_list,delivery_challan_delete,delivery_challan_pdf
from .sub_views.budgetform_add_view import budgetform_add,budgetform_list,budgetform_delete,budgetform_clone
from .sub_views.pk_Excess_Stock_view import pk_excess_stock_add,pk_excess_stock_list
from .sub_views.wh_highvaluecheck_add_view import highvalue_add,highvalue_list,highvalue_delete,highvalue_cancel,highvalue_report_list
from .sub_views.dispatch_add_view import gate_out_email
from .sub_views.reports_view import profit_loss_report
from .sub_views.sales_reports_view import sales_targets_view
from .sub_views.salesperson_chart_view import salesperson_chart
from .sub_views.salesperson_chart_view import monthly_summary
from .sub_views.salesperson_chart_view import salesperson_productivity_performance
from .sub_views.salesperson_chart_view import salescalls_details,sales_call_report
from .sub_views.salesperson_chart_view import targets_actuals
from .sub_views.salesperson_chart_view import salesperson_wise_chart,salesperson_wise_table
from .sub_views.salesperson_chart_view import businesswon_chart
from .sub_views.finance_reports_view import branch_profit_loss
from .sub_views.finance_reports_view import branch_unit_profit_loss
from .sub_views.finance_reports_view import finance_reports,businessmodel_PL,customerwise_PL,fin_profit_loss_view,expenses_report,ar_due_reports,budget_expense,budget_expense_mis,fin_mis,fin_mis_warehouse,overdue_jobs_report
from .sub_views.vehicleavailability_view import vehicle_availability_list
from .sub_views.transport_procurement_view import vehicle_procurement_add,vehicle_procurement_list,vehicle_procurement_delete
from .sub_views.wh_reports_view import wh_damage_report,wh_stock_report,wh_space_availability_report,wh_space_utilization_report,warehouse_dashboard
from .sub_views.gate_meeting_add_view import gatemeeting_add,gatemeeting_list,gatemeeting_delete,gate_meeting_send_email
from .sub_views.wh_reports_view import wh_damage_report,wh_stock_report,wh_space_availability_report
from .sub_views.opsauditscorecard_view import opsauditscorecard_add,opsauditscorecard_list,opsauditscorecard_delete,send_ops_audit_email
from .sub_views.performance_audit_view import performanceaudit_add,performanceaudit_list,performanceaudit_delete,send_performance_audit_email
from .sub_views.gate_meeting_add_view import gatemeeting_add,gatemeeting_list,gatemeeting_delete,gate_meeting_send_email
from .sub_views.transport_nav_view import transport_nav
from .sub_views.part_code_view import part_code_add,part_code_list,part_code_delete,get_stock_descriptions,get_part_code,partcode_search
from .sub_views.trans_fastag_view import fastag_enquiry_view, trans_fastag_export_excel
from .sub_views.trans_gps import track_vehicle_position,get_vehicle_data
from .sub_views.vendorratemaster_add_view import vendorratemaster_add,vendorratemaster_list,vendorratemaster_delete
from .sub_views.Location_master_view import location_master_add,location_master_list,location_master_delete
from .sub_views.trip_approval_view import trip_approval_view,update_trip_approval
from .sub_views.trip_highvaluecheck_view import trip_highvalue_add,trip_highvalue_list,trip_highvalue_delete,trip_highvalue_cancel
from .sub_views.backfill_view import backfill_one_record,backfill_preview,backfill_all_records,backfill_goods_weight
from .sub_views.wh_com_highvalue_view import highvalue_approval_view,update_highvalue_approval,highvalue_approval2_view,update_highvalue_approval2
from .sub_views.incident_report_view import incident_add,incident_list,incident_delete,incident_report,incident_send_email
from .sub_views.customer_claims_view import customer_claims_add,customer_claims_list,customer_claims_delete,customer_claims_report
from .sub_views.wrong_labelling_view import wrong_labelling_add,wrong_labelling_list,wrong_labelling_delete,wrong_labelling_report
from .sub_views.DGcargo_add_view import dg_cargo_add,dg_cargo_list,dg_cargo_delete,dg_cargo_approval_view,update_dg_cargo_approval,dg_cargo_report_list
from .sub_views.dmr_report_view import trip_report,trip_send_email,get_dmr_email_details
from .sub_views.driver_settlement_view import driver_settlement_add,driver_settlement_list,driver_settlement_delete,get_driver_details_from_master,get_trip_totalcost
from .sub_views.trip_settlement_view import trip_settlement_view,trip_settlement_edit
from .sub_views.trip_finance_approval_view import trip_finance_approval_view,update_trip_finance_approval
from .sub_views.haltingcharges_view import halting_charges_add,halting_list,halting_delete
from .sub_views.emailmaster_view import email_master_add,email_master_list,email_delete
from .sub_views.tripclosure_add_view import get_halting_charge, get_cancellation_charge
from .sub_views.driver_expense_view import driver_expense_add,driver_expense_list,driver_expense_delete,get_trip_charges
from .sub_views.driver_master_view import driver_add,driver_list,driver_delete,get_employee_driver_details,driver_autocomplete
from .sub_views.driver_expense_view import driver_expense_add,driver_expense_list,driver_expense_delete,filter_trips_by_date
from .sub_views.driver_salary_view import driver_salary_add, driver_salary_list, driver_salary_delete, get_driver_salary_details
from .sub_views.dmr_report_view import get_dmr_email_details
from .sub_views.maintenance_view import maintenance_add,maintenance_delete,maintenance_edit,maintenance_list,fetch_vehicle_details,fetch_filtered_vehicles,maintenance_pdf,manager_approval_list,manager_approve,finance_approval_list,finance_approve
from .sub_views.stock_maintenance_view import stock_maintenance_list, stock_maintenance_add, stock_maintenance_add_for_vendor, stock_maintenance_edit, stock_maintenance_delete, get_part_details
from .sub_views.trans_invoice_view import (trans_invoice_add,trans_invoice_list,trans_invoice_delete,fetch_customer_details,trans_invoice_list_woh,trans_invoice_remove_woh,trans_invoice_add_woh,trans_invoice_excel,trans_invoice_edit,trans_invoice_tally_excel)
from .sub_views.transport_reports_view import vehicle_log_report_view, trip_cancellation_report_view, ref_no_pending_report_view, vehicle_utilization_report_view, drivers_advance_report_view, invoice_pending_report_view,vendor_p_l_mkt_report_view,vendor_p_l_attached_report_view,get_vehicles_by_vendor,whatsapp_delivery_status_report_view,daily_trip_count_report_view, own_vehicle_pl_report_view, claim_pending_report_view, halting_report_view, halting_report_ajax_view, maintenance_report_view, insurance_renewal_report_view, diesel_vs_revenue_report_view, own_vs_market_sales_report_view,enquiry_pending_report_view, enquiry_pending_report_ajax_view, driver_balance_report_view, pod_pending_report_view, pod_pending_report_ajax_view, movementwise_pl_report_view, movementwise_pl_report_ajax_view, customerwise_pl_report_view, customerwise_pl_report_ajax_view, location_pl_report_view, time_analysis_report_view, mileage_report_view, vendor_bills_pending_maintenance_report_view, vendor_bills_pending_mkt_att_report_view, transport_mis
from .sub_views.market_bill_view import market_bill_add, market_bill_list, market_bill_edit, market_bill_delete, get_trips_by_vendor, market_bill_upload, market_mail_upload
from .sub_views.customer_registration_view import customer_register, customer_registration_list, customer_registration_approve, customer_registration_reject, ajax_search_customers, ajax_check_customer_code
from .sub_views.maintenance_bill_view import maintenance_bill_add, maintenance_bill_list, fetch_maintenance_bill_details, get_maintenance_records_by_vehicle, maintenance_bill_edit, maintenance_bill_delete
from .sub_views.customer_enquiry_view import customer_enquiry_add, customer_enquiry_edit, customer_enquiry_list, customer_dashboard, customer_shipment_tracking, customer_track_vehicle, download_pod, download_dmr, ajax_get_vehicle_types, customer_documents, customer_profile, customer_support
from .sub_views.customer_login_view import customer_login, ajax_get_customer_departments
from .sub_views.attached_bill_view import attached_bill_add, attached_bill_list, attached_bill_edit, attached_bill_delete, get_attached_vehicle_details, get_vehicles_by_vendor, attached_bill_upload, attached_bill_summary
from .sub_views.trans_customer_claims_view import trans_customer_claims_add, trans_customer_claims_list, trans_customer_claims_delete, fetch_trip_details_by_cnote
from .sub_views.charge_master_view import charge_master_add,charge_master_delete,charge_master_list
from .sub_views.sale_enquiry_view import sale_enquiry_list, sale_enquiry_add, sale_enquiry_delete, get_customer_code, get_sale_details, mc_tours_calendar_events
from .sub_views.invoice_documents_view import invoice_documents_list, invoice_documents_add
from .sub_views.pk_production_dashboard_view import pk_production_dashboard, update_production_status
from .sub_views.pk_quality_check_view import pk_quality_check_list, pk_quality_check_add, get_job_details_for_qc, pk_quality_check_pdf
from .sub_views.pk_tool_master_view import pk_tool_master_list, pk_tool_master_add, pk_tool_master_delete
from .sub_views.privacy_policy_view import privacy_policy
from .sub_views.deletion_log_view import deletion_log_list
