# Generated by Django 4.0.4 on 2022-05-18 11:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(default='', max_length=10)),
                ('asset_model', models.CharField(max_length=30)),
                ('asset_make', models.CharField(max_length=30)),
                ('asset_serial_num1', models.CharField(default='', max_length=10)),
                ('asset_assignedon', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_order_number', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_enquiry_number', models.CharField(max_length=10)),
                ('enq_customer_name', models.CharField(choices=[('DHL', 'DHL'), ('EXP', 'EXP'), ('OTHERS', 'OTHERS')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cat_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=100, null=True)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_movement_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_mov_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_stock_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wh_stock_invoice', models.CharField(max_length=20)),
                ('wh_stock_customer_name', models.CharField(max_length=20)),
                ('wh_stock_arrival_date', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_unloading_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_unloading_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_FRD_time', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_invoice_value', models.IntegerField(blank=True, null=True)),
                ('wh_stock_amount_in', models.IntegerField(blank=True, null=True)),
                ('wh_stock_transporters', models.CharField(blank=True, max_length=100, null=True)),
                ('wh_stock_truck_number', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_truck_type', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_consigner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wh_stock_consignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wh_stock_docs_received', models.CharField(blank=True, max_length=10, null=True)),
                ('wh_stock_HAWB', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_MAWB', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_destination', models.CharField(blank=True, max_length=30, null=True)),
                ('wh_stock_case_number', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_invoice_weight', models.IntegerField(blank=True, null=True)),
                ('wh_stock_CBM', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_eway_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_fumigation_status', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_location', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_days_in_wh', models.IntegerField(blank=True, null=True)),
                ('wh_stock_ship_date', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_out_time', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_labels_pasted_by', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_name', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_lic', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_name_out', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_contact_out', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_driver_lic_out', models.CharField(blank=True, max_length=250, null=True)),
                ('wh_stock_arrival_date_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_unloading_start_time_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_unloading_end_time_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_FRD_time_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_transporters_out', models.CharField(blank=True, max_length=100, null=True)),
                ('wh_stock_truck_number_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_truck_type_out', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_stock_invoice_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.currency_type')),
                ('wh_stock_movement_type', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.stock_movement_type')),
                ('wh_stock_type', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.stock_type')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_goods_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wh_goods_invoice', models.CharField(blank=True, max_length=20, null=True)),
                ('wh_goods_pieces', models.IntegerField()),
                ('wh_goods_length', models.IntegerField()),
                ('wh_goods_width', models.IntegerField()),
                ('wh_goods_height', models.IntegerField()),
                ('wh_goods_weight', models.IntegerField()),
                ('wh_goods_volume_weight', models.IntegerField()),
                ('wh_goods_package_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.package_type')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_name', models.CharField(max_length=100)),
                ('vend_description', models.CharField(default='', max_length=100)),
                ('vend_contact', models.CharField(max_length=10)),
                ('vend_contact_per', models.CharField(default='', max_length=50)),
                ('vend_gstin', models.CharField(default='', max_length=10)),
                ('vend_designation', models.CharField(max_length=30)),
                ('vend_email', models.CharField(max_length=50)),
                ('vend_zip', models.CharField(max_length=10)),
                ('vend_address', models.CharField(max_length=300)),
                ('vend_city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.city')),
                ('vend_country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.country')),
                ('vend_state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.state')),
                ('vend_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_start_date', models.CharField(max_length=10)),
                ('ser_end_date', models.CharField(max_length=10)),
                ('ser_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ser_asset', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.assetinfo')),
                ('ser_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
                ('ser_vendor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vendor_info')),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_description', models.CharField(default='', max_length=50)),
                ('prod_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.prod_type')),
            ],
        ),
        migrations.CreateModel(
            name='Location_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('loc_con_per_phone', models.CharField(max_length=10)),
                ('loc_con_per_name', models.CharField(default='', max_length=50)),
                ('loc_con_per_email', models.CharField(max_length=50)),
                ('loc_zipcode', models.CharField(max_length=10)),
                ('loc_address', models.CharField(max_length=300)),
                ('loc_city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.city')),
                ('loc_country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.country')),
                ('loc_state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.state')),
                ('loc_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_name', models.CharField(max_length=40)),
                ('ins_start_date', models.CharField(max_length=10)),
                ('ins_expiry_date', models.CharField(max_length=10)),
                ('ins_units', models.CharField(default='', max_length=10)),
                ('ins_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
                ('ins_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.insurance_type')),
                ('ins_vendor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vendor_info')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad')], default='', max_length=10)),
                ('designation', models.CharField(choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Driver', 'Driver'), ('Helper', 'Helper')], default='', max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
                ('employee_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
            ],
        ),
        migrations.CreateModel(
            name='Department_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_con_per_phone', models.CharField(max_length=10)),
                ('dept_con_per_name', models.CharField(default='', max_length=50)),
                ('dept_con_per_email', models.CharField(max_length=50)),
                ('dept_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.state'),
        ),
        migrations.CreateModel(
            name='Assign_asset_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AA_assingedto', models.CharField(blank=True, max_length=20, null=True)),
                ('AA_assignedon', models.CharField(blank=True, max_length=20, null=True)),
                ('AA_assignedby', models.CharField(blank=True, max_length=20, null=True)),
                ('AA_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('AA_asset_number', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.assetinfo')),
            ],
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_assignedto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.myuser'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_insurance_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.insurance_info'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.location_info'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.product_info'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vendor_info'),
        ),
    ]
