# Generated by Django 4.1.2 on 2023-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_designation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_zip',
            field=models.CharField(max_length=10),
        ),
    ]
