# Generated by Django 4.0.4 on 2022-05-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_name', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peo_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_name', models.CharField(default='', max_length=100)),
                ('peo_age', models.IntegerField(default='', max_length=3)),
                ('peo_mob', models.IntegerField(default='', max_length=10)),
                ('peo_address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stud_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(default='', max_length=100)),
                ('stud_age', models.IntegerField(default='', max_length=3)),
                ('stud_eng', models.IntegerField(default='', max_length=3)),
                ('stud_tamil', models.IntegerField(default='', max_length=3)),
                ('stud_math', models.IntegerField(default='', max_length=3)),
                ('stud_social', models.IntegerField(default='', max_length=3)),
                ('stud_science', models.IntegerField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DamagereportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_GRN_num', models.CharField(default='', max_length=20, null=True)),
                ('dam_damage_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.damageinfo')),
            ],
        ),
    ]
