# Generated by Django 4.2.9 on 2024-09-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatein_pre_info',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='expenseinfo',
            name='exp_unit_1',
            field=models.ManyToManyField(db_column='exp_unit_1', related_name='exp_unit_1', to='sms_app.unitinfo'),
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='exp_unit',
            field=models.ForeignKey(blank=True, db_column='exp_unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_unit', to='sms_app.unitinfo'),
        ),
        migrations.AlterField(
            model_name='salesinfo',
            name='s_joint_call_name',
            field=models.ManyToManyField(db_column='s_joint_call_name', related_name='s_joint_call_name', to='sms_app.myuser'),
        ),
    ]
