# Generated by Django 4.2.9 on 2024-09-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_alter_gatein_pre_info_options_expenseinfo_exp_unit_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatein_pre_info',
            options={'ordering': ['-id']},
        ),
    ]
