# Generated by Django 4.0.4 on 2022-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_damageinfo_peo_reg_stud_reg_damagereportinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_eng',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_math',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_science',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_social',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stud_reg',
            name='stud_tamil',
            field=models.IntegerField(default=''),
        ),
    ]
