# Generated by Django 4.1.2 on 2023-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_remove_vendor_info_vend_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_info',
            name='vend_vend_remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
