# Generated by Django 4.0.4 on 2022-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_alter_stud_reg_stud_age_alter_stud_reg_stud_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peo_reg',
            name='peo_age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='peo_reg',
            name='peo_mob',
            field=models.IntegerField(default=''),
        ),
    ]
