# Generated by Django 4.0.4 on 2022-05-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_alter_peo_reg_peo_age_alter_peo_reg_peo_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationmasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_wh_unit', models.CharField(default='', max_length=20)),
                ('lm_areaside', models.CharField(default='', max_length=10)),
                ('lm_size', models.IntegerField(default='')),
                ('lm_wh_location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.location_info')),
            ],
        ),
    ]
