# Generated by Django 4.1.2 on 2023-02-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_vendor_info_vend_vend_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_info',
            old_name='vend_vend_remarks',
            new_name='vend_remarks',
        ),
    ]
