# Generated by Django 4.0.4 on 2022-05-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_locationmasterinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_info',
            name='loc_con_per_email',
        ),
        migrations.RemoveField(
            model_name='location_info',
            name='loc_con_per_name',
        ),
        migrations.RemoveField(
            model_name='location_info',
            name='loc_con_per_phone',
        ),
    ]
