# Generated by Django 4.1.2 on 2023-02-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_rename_vend_vend_remarks_vendor_info_vend_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_info',
            name='vend_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor_info',
            name='vend_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor_info',
            name='vend_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.myuser'),
        ),
    ]
