# Generated by Django 4.1.2 on 2023-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_vendor_info_vend_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
