# Generated by Django 4.1.2 on 2023-02-14 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_alter_vendor_info_vend_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_updated_by',
            field=models.ForeignKey(db_column='en_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_updated_by', to='sms_app.myuser'),
        ),
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_lastmodifiedby',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
