# Generated by Django 4.1.2 on 2023-02-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_enquirynoteinfo_en_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirynoteinfo',
            name='en_raisedby',
        ),
    ]
