# Generated by Django 4.1.2 on 2023-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_remove_enquirynoteinfo_en_raisedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirynoteinfo',
            name='en_raisedon',
        ),
    ]
