# Generated by Django 4.1.2 on 2023-02-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0010_remove_enquirynoteinfo_en_raisedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_agencycharges',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_agencyname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_axletype',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.axletypeinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_batterynumber',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_batterywarrantydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_body',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.bodyinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_bpclcard',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_budgetexpense',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehiclecategoryinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_chassisnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_containersize',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_enginenumber',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fakexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fastagid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fcamount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fccopy',
            field=models.ForeignKey(blank=True, db_column='vm_fccopy', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_fccopy', to='sms_app.statuslist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fcdate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fcexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fireextexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fireextinguisher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_firstaidkit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_fueltype',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.fueltypeinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_gprssimid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_gprstrackingid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_icvvalue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_insurancecopy',
            field=models.ForeignKey(blank=True, db_column='vm_insurancecopy', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_insurancecopy', to='sms_app.statuslist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_insurancetype',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.insurance_type'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_millage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_mobileappdeviceid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_ncb',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_numberoftyres',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_ofdepreciation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_ownership',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.ownershipinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permitamount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permitcopy',
            field=models.ForeignKey(blank=True, db_column='vm_permitcopy', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_permitcopy', to='sms_app.statuslist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permitdate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permitexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_permittype',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.permittypeinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_policy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_policyexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_pollutioncertificate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_pollutioncertificateamt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_pollutioncertificatecopy',
            field=models.ForeignKey(blank=True, db_column='vm_pollutioncertificatecopy', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_pollutioncertificatecopy', to='sms_app.statuslist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_pollutioncertificatedate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_potenialrevenue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_premium',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_primarydrivermob',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_primarydrivername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_receipt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_registrationdate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_registrationnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_roadtaxamount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_roadtaxcopy',
            field=models.ForeignKey(blank=True, db_column='vm_roadtaxcopy', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_roadtaxcopy', to='sms_app.statuslist'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_roadtaxexpirydate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_roadtaxreceipt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_roadtaxreceiptdate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_rtoname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_secondarydrivermob',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_secondarydrivername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_stephanietyre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_stephanietyremake',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tonnage',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_toolboxcontent1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_toolboxcontent2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_toolboxcontent3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_toolboxcontent4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_toolboxcontent5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tyre1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tyre2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tyre3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tyre4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_tyremake',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_valueofvehicle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_vehiclecolour',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehiclecolourinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_vehiclemanufacturer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.vhmanufacturerinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_vehiclemodel',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehiclemodelinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_vehicletype',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehicletypeinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclemasterinfo',
            name='vm_yearofdepreciation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
