# Generated by Django 4.1.2 on 2023-02-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0013_alter_vendor_info_vend_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_info',
            name='dispatch_HAWB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch_info',
            name='dispatch_MAWB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch_info',
            name='dispatch_eWaybill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gatein_info',
            name='gatein_po_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.location_info'),
        ),
    ]
