# Generated by Django 4.1.2 on 2023-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0014_alter_dispatch_info_dispatch_hawb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_customeremail',
            field=models.EmailField(max_length=100),
        ),
    ]
