# Generated by Django 4.1.2 on 2023-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0015_alter_enquirynoteinfo_en_customeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='cu_email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
