# Generated by Django 4.1.2 on 2023-02-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0016_alter_customerinfo_cu_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentdetailinfo',
            name='co_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentdetailinfo',
            name='co_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_lastmodifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.myuser'),
        ),
    ]
