# Generated by Django 4.1.2 on 2023-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0017_consignmentdetailinfo_co_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_consignmentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_dateofissue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_dateofvalidity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
