# Generated by Django 4.1.2 on 2023-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0018_alter_consignmentdetailinfo_co_consignmentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_consignmentdetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_tripdetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_vehicledetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_enquirynumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
