# Generated by Django 4.1.2 on 2023-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0019_enquirynoteinfo_en_consignmentdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_consignmentdetails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_tripdetails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_vehicledetails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
