# Generated by Django 4.1.2 on 2023-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0020_alter_enquirynoteinfo_en_consignmentdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_consignee',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_consigner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='consignmentdetailinfo',
            name='co_consignerinvoice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_othercustomer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
