# Generated by Django 4.1.2 on 2023-02-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0021_alter_consignmentdetailinfo_co_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetailinfo',
            name='ve_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetailinfo',
            name='ve_updated_by',
            field=models.ForeignKey(db_column='ve_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ve_updated_by', to='sms_app.myuser'),
        ),
        migrations.AlterField(
            model_name='vehicledetailinfo',
            name='ve_lastmodifiedby',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
