# Generated by Django 4.1.2 on 2023-02-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0022_vehicledetailinfo_ve_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetailinfo',
            old_name='ve_lastmodifiedby',
            new_name='ve_updated_at',
        ),
    ]
