# Generated by Django 4.1.2 on 2023-02-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0023_rename_ve_lastmodifiedby_vehicledetailinfo_ve_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_drivername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_drivernumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_transportbusinesstype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.trbusinesstypeinfo'),
        ),
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_vehiclenumber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehiclenumberinfo'),
        ),
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_vehiclesource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehiclesourceinfo'),
        ),
        migrations.AddField(
            model_name='tripdetailinfo',
            name='tr_vehicletype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehicletypeinfo'),
        ),
    ]
