# Generated by Django 4.1.2 on 2023-02-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0024_tripdetailinfo_tr_drivername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetailinfo',
            name='tr_deliveryimages',
        ),
        migrations.RemoveField(
            model_name='tripdetailinfo',
            name='tr_proofofdelivery',
        ),
    ]
