# Generated by Django 4.1.2 on 2023-02-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0025_remove_tripdetailinfo_tr_deliveryimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetailinfo',
            name='tr_tripstatus',
        ),
    ]
