# Generated by Django 4.1.2 on 2023-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0026_remove_tripdetailinfo_tr_tripstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetailinfo',
            name='tr_endingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetailinfo',
            name='tr_startingdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
