# Generated by Django 4.0.4 on 2022-09-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0028_alter_whratemasterinfo_whrm_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatein_pre_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatein_pre_transporter', models.CharField(blank=True, max_length=100, null=True)),
                ('gatein_pre_truck_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gatein_pre_driver', models.CharField(blank=True, max_length=20, null=True)),
                ('gatein_pre_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gatein_pre_DL_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gatein_pre_arrival_date_time', models.DateTimeField(null=True)),
                ('gatein_pre_otl', models.CharField(blank=True, max_length=20, null=True)),
                ('gatein_pre_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('gatein_pre_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gatein_pre_status', models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist')),
                ('gatein_pre_truck_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.vehicletypeinfo')),
            ],
        ),
    ]
