# Generated by Django 4.1.2 on 2023-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0028_remove_tripdetailinfo_tr_lastmodifiedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetailinfo',
            name='tr_shipmentdetails',
        ),
        migrations.AlterField(
            model_name='vendor_info',
            name='vend_gstin',
            field=models.CharField(default='', max_length=15),
        ),
    ]
