# Generated by Django 4.1.2 on 2023-02-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0029_remove_tripdetailinfo_tr_shipmentdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripclosureinfo',
            name='tc_lastmodifiedby',
        ),
        migrations.AddField(
            model_name='tripclosureinfo',
            name='tc_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tripclosureinfo',
            name='tc_tripnumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tripclosureinfo',
            name='tc_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tripclosureinfo',
            name='tc_updated_by',
            field=models.ForeignKey(db_column='tc_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tc_updated_by', to='sms_app.myuser'),
        ),
    ]
