# Generated by Django 4.1.2 on 2023-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0030_remove_tripclosureinfo_tc_lastmodifiedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirynoteinfo',
            name='en_tripclosure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
