# Generated by Django 4.1.2 on 2023-02-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0031_enquirynoteinfo_en_tripclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='sms_app.statuslist'),
        ),
    ]
