# Generated by Django 4.1.2 on 2023-02-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0032_alter_enquirynoteinfo_en_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirynoteinfo',
            old_name='en_lastmodifiedby',
            new_name='en_updatedon',
        ),
    ]
