# Generated by Django 4.1.2 on 2023-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0033_rename_en_lastmodifiedby_enquirynoteinfo_en_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirynoteinfo',
            name='en_customercode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
