# Generated by Django 4.1.2 on 2023-02-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0034_alter_enquirynoteinfo_en_customercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirynoteinfo',
            name='en_othercustomer',
        ),
    ]
