# Generated by Django 4.1.2 on 2023-03-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0036_alter_warehouse_goods_info_wh_po_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatein_info',
            options={'ordering': ['gatein_invoice']},
        ),
        migrations.AlterField(
            model_name='warehouse_goods_info',
            name='wh_goods_invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sms_app.gatein_info'),
        ),
    ]
