# Generated by Django 4.1.2 on 2023-03-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0037_alter_gatein_info_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_goods_info',
            name='wh_goods_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.gatein_info'),
        ),
    ]
